version: "3.9"
services:
  go-api:
    build: ./go-api
    image: ${AZURE_CONTAINER_REGISTRY}.azurecr.io/go-api-go-api:latest
    environment:
      - PROMETHEUS_TARGET_PORT=${PROMETHEUS_TARGET_PORT}
    ports:
      - ${GO_API_WEB_PORT}:${GO_API_WEB_PORT}
      - ${PROMETHEUS_TARGET_PORT}:${PROMETHEUS_TARGET_PORT}
    domainname: ${DOMAIN_NAME}
    deploy:
      resources:
        reservations:
          cpus: '3.8'
          memory: '2.0G'
        limits:
          cpus: '3.8'
          memory: '2.0G'


  go-load:
    build: ./go-load
    image: ${AZURE_CONTAINER_REGISTRY}.azurecr.io/go-api-go-load:latest
    environment:
      - GO_LOAD_TARGET_HOST=${GO_LOAD_TARGET_HOST}
      - GO_LOAD_NUM_CLIENTS=${GO_LOAD_NUM_CLIENTS}
      - GO_LOAD_RUN_TIME=${GO_LOAD_RUN_TIME}
      - EXPERIMENT_WORKLOAD=${EXPERIMENT_WORKLOAD}
    depends_on:
      - go-api
    volumes:
      - heliobench:/home/experiment
    domainname: ${DOMAIN_NAME}
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: '0.1G'
        limits:
          cpus: '0.1'
          memory: '0.1G'


volumes:
  heliobench:
    driver: azure_file
    driver_opts:
      share_name: ${AZURE_FILE_SHARE_NAME}
      storage_account_name: ${AZURE_STORAGE_ACCOUNT_NAME}