version: "3.9"
services:
  go-api:
    build: ./go-api
    environment:
      - PROMETHEUS_TARGET_PORT=${PROMETHEUS_TARGET_PORT}
    ports:
      - 8080:8080
      - ${PROMETHEUS_TARGET_PORT}:${PROMETHEUS_TARGET_PORT}
    networks:
      - HelioBench-network

  go-load:
    build: ./go-load
    environment:
      - GO_LOAD_TARGET_HOST=http://go-api:8080
      - GO_LOAD_NUM_CLIENTS=3
      - GO_LOAD_RUN_TIME=1m
    depends_on:
      - go-api
    volumes:
      - HelioBench:/home/experiment
    networks:
      - HelioBench-network

volumes:
  HelioBench:
    external: true

networks:
  HelioBench-network:
    external: true