version: "3.9"
services:
  go-api:
    build: ./go-api
    ports:
      - 8080:8080
      - 9100:9100

  go-load:
    build: ./go-load
    environment:
      - HOST=http://go-api:8080
      - NUM_CLIENTS=30
      - TIME=10h
    depends_on:
      go-api:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      go-api:
        condition: service_started