version: "3.9"
services:
  memcached:
    build: ./memcached
    ports:
      - 11211:11211
      - 9100:9100

  memaslap:
    build: ./memaslap
    depends_on:
      memcached:
        condition: service_started
    entrypoint: ["./libmemcached-1.0.18/clients/memaslap", "--servers=memcached:11211" , "-t 2h", "-S 5s"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      memcached:
        condition: service_started