version: "3.9"
services:
  memcached:
    build: ./memcached
    environment:
      - PROMETHEUS_TARGET_PORT=${PROMETHEUS_TARGET_PORT}
    ports:
      - 11211:11211
      - ${PROMETHEUS_TARGET_PORT}:${PROMETHEUS_TARGET_PORT}
    networks:
      - HelioBench-network

  memaslap:
    build: ./memaslap
    depends_on:
      memcached:
        condition: service_started
    environment:
      - SERVERS=memcached:11211
      - STAT_FREQ=10s
      - TIME=1m
      - EXPERIMENT_WORKLOAD=memcached
    volumes:
      - HelioBench:/home/experiment
    networks:
      - HelioBench-network

volumes:
  HelioBench:
    external: true

networks:
  HelioBench-network:
    external: true