version: "3.9"
services:
  text-analysis:
    build: .
    image: ${AZURE_CONTAINER_REGISTRY}.azurecr.io/${EXPERIMENT_WORKLOAD}-${EXPERIMENT_WORKLOAD}-dev:latest
    hostname: text-analysis
    ports:
      - ${PROMETHEUS_TARGET_PORT}:${PROMETHEUS_TARGET_PORT}
    environment:
      - PROMETHEUS_TARGET_PORT=${PROMETHEUS_TARGET_PORT}
      - EXPERIMENT_WORKLOAD=${EXPERIMENT_WORKLOAD}
    restart: on-failure
    volumes:
      - heliobench:/home/experiment
    domainname: ${EXPERIMENT_WORKLOAD}

volumes:
  heliobench:
    driver: azure_file
    driver_opts:
      share_name: ${AZURE_FILE_SHARE_NAME}
      storage_account_name: ${AZURE_STORAGE_ACCOUNT_NAME}