version: "3.9"
services:
  text-analysis:
    build: .
    hostname: text-analysis
    ports:
      - "${PROMETHEUS_TARGET_PORT}:${PROMETHEUS_TARGET_PORT}"
    environment:
      - PROMETHEUS_TARGET_PORT=${PROMETHEUS_TARGET_PORT}
      - EXPERIMENT_WORKLOAD=text-analysis
    restart: on-failure
    networks:
      - HelioBench-network
    volumes:
      - HelioBench:/home/experiment

volumes:
  HelioBench:
    external: true

networks:
  HelioBench-network:
    external: true