version: "3.9"
services:
  alexnet:
    build: ./
    hostname: alexnet
    ports:
      - "${PROMETHEUS_TARGET_PORT}:${PROMETHEUS_TARGET_PORT}"
    environment:
      - PROMETHEUS_TARGET_PORT=${PROMETHEUS_TARGET_PORT}
      - EXPERIMENT_WORKLOAD=${EXPERIMENT_WORKLOAD}
    restart: on-failure
    networks:
      - HelioBench-network
    volumes:
      - HelioBench:/home/experiment

volumes:
  HelioBench:
    external: true

networks:
  HelioBench-network:
    external: true