
TEN_BYTE_ARTICLE = {
    "description":"10B Article",
    "description":"10B Article",
    "content" : "Lorem dui."
}

HUNDRED_BYTE_ARTICLE = {
    "description":"100B Article",
    "description":"100B Article",
    "content" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at ultrices nisi. Mauris at laoreet."
}

THOUSAND_BYTE_ARTICLE = {
    "description":"1000B Article",
    "description":"1000B Article",
    "content" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris efficitur tortor in fringilla viverra. Proin quis arcu non enim auctor ornare ac suscipit odio. Morbi dictum, eros ut tincidunt efficitur, magna diam fermentum magna, vel varius ex turpis et odio. Donec dapibus vehicula nulla, quis posuere neque vulputate sit amet. Ut tristique metus et lectus fringilla, in ornare nisl sagittis. Praesent pharetra lacus ligula, a euismod diam tempor a. Fusce at dui diam. Donec id elit euismod, volutpat lorem at, ullamcorper risus. Maecenas laoreet odio vitae nisl eleifend laoreet. Sed rhoncus enim a interdum euismod. Etiam arcu ante, tincidunt in metus eget, faucibus semper tellus. Donec efficitur condimentum consectetur. Fusce suscipit, metus eu sagittis ultricies, leo justo tincidunt justo, nec fermentum nisi lacus quis turpis. In vehicula dui metus, at mollis sapien elementum sed. Vivamus ultrices lacus et velit rhoncus consequat. Nullam fringilla massa quis erat finibus, a fringilla nec."
}

TENTHOUSAND_BYTE_ARTICLE = {
    "description":"10B Article",
    "description":"10B Article",
    "content" : '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vehicula massa eu condimentum feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas sit amet sem suscipit ante porttitor commodo eu ut felis. Donec sit amet tincidunt velit, molestie lacinia nisl. Cras commodo, odio in egestas porttitor, ex elit dignissim metus, eget malesuada ligula tellus a quam. Proin auctor dolor a lectus feugiat, in egestas lorem iaculis. In porta tristique quam id euismod.

Aenean accumsan a nisi in fermentum. Nam tellus lectus, condimentum at urna at, finibus vehicula ante. In imperdiet ante vel risus tempor vehicula. Nulla congue enim ut est hendrerit consectetur. Aenean vehicula placerat mi nec ultrices. Sed vel tellus vitae ligula ultrices blandit ac eu orci. Aenean ac vehicula metus. Cras elit ex, mattis id pretium quis, ultrices et ligula. Nullam ut placerat sapien. Morbi venenatis mi fermentum nisl pulvinar, vitae lobortis ipsum rhoncus. Vestibulum congue nunc sed elit laoreet scelerisque. Morbi vitae massa eget orci placerat rhoncus vel maximus eros. Integer dignissim neque a augue placerat sagittis. Nulla consectetur, sapien a interdum varius, eros arcu mattis ligula, sed rutrum quam diam sollicitudin mi.

Nunc consequat eget libero ac porta. Pellentesque eu auctor odio. Donec ullamcorper quam ligula, vel dapibus nulla dictum ac. Vestibulum et orci vel augue luctus sollicitudin. Nunc odio ex, porttitor vel eros in, tincidunt iaculis ipsum. Nunc malesuada id ex non rutrum. Curabitur ut porttitor nisl. Fusce sed convallis nulla.

Nunc sem eros, viverra et ante sed, tincidunt volutpat est. Vestibulum vulputate vel metus eget cursus. Morbi vitae iaculis lectus, non placerat justo. Donec ultricies sagittis arcu nec feugiat. Nam egestas odio non nunc finibus viverra. Integer sed nunc lorem. Mauris nec velit non quam finibus ultricies. Cras dignissim mi eu tristique pellentesque. Etiam nec tincidunt tortor, sit amet dictum justo. Aenean id turpis sagittis, consectetur arcu et, sagittis nisi. Maecenas massa ipsum, sollicitudin sed ipsum eu, auctor fermentum nunc. Vestibulum sed massa pulvinar, eleifend urna eget, posuere ante. Duis finibus et felis at auctor. Curabitur a odio a justo ullamcorper aliquam suscipit at odio. Donec ut justo ut tortor elementum suscipit. Suspendisse venenatis, turpis eu convallis semper, ligula odio faucibus nunc, id hendrerit tortor risus quis turpis.

Aliquam egestas, lorem non aliquet consectetur, elit eros sollicitudin ex, vel rutrum nulla elit vitae nunc. In consectetur nec quam ullamcorper dictum. Vivamus tincidunt cursus massa, eget sagittis sapien elementum nec. Etiam id gravida felis, eget aliquam magna. Proin pharetra, elit vitae hendrerit malesuada, mi odio sollicitudin sapien, non ornare tellus enim tincidunt augue. Sed et tortor ac lorem facilisis sodales. Fusce interdum venenatis erat, vitae mattis leo tincidunt laoreet. Nullam sollicitudin tempor tempor. Duis rhoncus vitae risus eu sodales. Cras sodales diam at mattis imperdiet. Morbi nec magna magna. In vel imperdiet quam. In luctus sapien a orci fermentum volutpat. Nulla mattis leo a lectus lacinia, nec porttitor nulla lacinia. Sed nec turpis tempus, malesuada lorem quis, aliquam nibh. Vivamus a dolor vitae lorem ullamcorper tincidunt eget vitae nisl.

Praesent eleifend porttitor pharetra. Morbi vulputate orci at tortor facilisis, nec dictum risus volutpat. Integer convallis mi sit amet neque scelerisque, ut laoreet erat blandit. Pellentesque sit amet ante diam. Nulla vulputate id augue id tincidunt. Nam tempor sodales ipsum sed fermentum. Aenean quis massa pretium, aliquet nulla vitae, tristique purus. Proin malesuada erat elementum lorem blandit tempus. Maecenas porttitor nisi in risus egestas dapibus. Sed quis mattis lectus. Vivamus tincidunt nunc non enim porttitor, ut iaculis nunc bibendum. Aliquam neque libero, maximus quis lacus eget, posuere rutrum massa. Suspendisse pretium maximus quam, in aliquet risus tempor id. Praesent at vulputate diam, sed interdum nisl. Aliquam faucibus lorem nulla, ac consectetur libero tincidunt in. Etiam ac mollis ex, eu efficitur diam.

Mauris tortor lacus, consectetur eget eros eu, volutpat tincidunt nunc. In hac habitasse platea dictumst. Sed id mauris sit amet nulla interdum posuere. Quisque congue odio a molestie rutrum. Suspendisse vehicula elementum dui posuere lobortis. Curabitur mollis rutrum nisl, sit amet efficitur lectus eleifend nec. Sed pulvinar dapibus dignissim. Aliquam et sollicitudin purus, sit amet blandit elit. Curabitur eget rhoncus tellus. Donec vitae enim nec nibh dictum porta et vel neque. Vivamus porttitor purus eu augue convallis, efficitur suscipit sapien blandit. Integer at tortor risus.

Proin hendrerit vel risus eu interdum. Aliquam varius risus in velit aliquet varius. Cras et porttitor justo. Praesent laoreet auctor eros, ullamcorper semper leo bibendum sed. Nunc quis molestie enim. Quisque bibendum erat vitae volutpat fermentum. Morbi sapien quam, lacinia quis tempor ut, tempus vitae augue. Suspendisse elit eros, cursus non tortor imperdiet, tincidunt varius ante. Integer sapien sem, eleifend ut odio at, lacinia luctus nibh. In eget nibh in purus convallis sodales non nec nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

In placerat hendrerit urna a laoreet. Fusce non turpis felis. Curabitur mollis auctor erat. Integer sollicitudin consectetur ultrices. Morbi condimentum luctus sapien. Maecenas auctor dui sit amet nunc sagittis, vitae feugiat justo condimentum. Ut in dolor mattis lectus rhoncus lobortis ut et elit. Etiam in ex porta ante condimentum efficitur in ut neque. Nam pharetra condimentum enim imperdiet gravida. Donec fermentum felis eu quam ornare, vitae commodo purus mattis. Morbi rutrum congue lorem. Vivamus fermentum massa odio, ac ultricies mauris interdum quis.

Pellentesque euismod venenatis tortor non pulvinar. Curabitur quis mattis nulla, vel tincidunt turpis. Proin a consequat magna, vitae mattis nisi. Curabitur pretium, justo vitae fringilla rhoncus, dolor metus fermentum metus, sed interdum augue urna a magna. Proin imperdiet ipsum ut risus sagittis ultricies. Phasellus porttitor scelerisque enim non eleifend. Pellentesque viverra porttitor orci, ac imperdiet nulla tristique imperdiet. Sed pulvinar justo consectetur nulla vehicula facilisis. Cras dapibus, lorem in viverra blandit, ipsum ipsum commodo libero, vitae egestas elit est id orci. Phasellus porta nisi sed efficitur consectetur. Pellentesque leo nunc, convallis sit amet imperdiet eu, sollicitudin quis neque. In leo mauris, dignissim sit amet diam ac, sagittis porttitor mi. Proin et lacinia dui. Phasellus in lorem tortor.

Donec consequat lacus ut ligula imperdiet, sed faucibus metus ornare. Aenean vitae dolor quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut maximus diam sit amet ligula semper lacinia. Cras at massa vitae ligula euismod vehicula. Pellentesque sit amet elit sed orci molestie auctor. Nullam nulla massa, tempus id felis sed, auctor dapibus mi. Proin condimentum velit scelerisque, pharetra erat egestas, sagittis lectus. Ut pharetra nisl non tortor ornare varius. Morbi aliquet nec ligula eu accumsan. Sed consequat vestibulum est, sed vehicula dolor fermentum eu. Nunc eget ipsum nec risus imperdiet condimentum vel quis dolor. Quisque nec vulputate libero. Maecenas ante lorem, imperdiet eu dui in, gravida tristique diam. Nam pellentesque ipsum a arcu posuere, non volutpat est feugiat. Aenean eget suscipit augue.

Integer mattis ullamcorper diam, eu facilisis ante venenatis nec. Sed mollis lacus ornare, mollis ante id, congue dolor. Proin congue erat nec orci semper, a egestas massa porttitor. Morbi volutpat fringilla lectus a blandit. Aenean gravida, mauris eu auctor accumsan, erat diam lacinia augue, vel suscipit magna mi ut erat. Maecenas ac consectetur sapien, ut sagittis metus. Curabitur nec sapien libero. Suspendisse molestie, tellus sit amet sollicitudin molestie, sapien odio aliquam purus, id hendrerit mi mi nec leo. Fusce arcu libero, gravida vel mauris sed, rutrum egestas ipsum. Donec dapibus malesuada leo, vitae facilisis dolor venenatis pharetra.

Nulla ac pretium dui. Fusce efficitur eleifend risus in dictum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse sit amet sem lorem. Fusce justo arcu, condimentum at ligula a, cursus molestie lectus. Sed dapibus dapibus velit, a ultricies purus aliquet ut. Mauris sit amet pharetra justo, varius gravida urna.

Curabitur blandit semper massa quis rutrum. Ut quis ante convallis, tempus ex in, gravida risus. Nulla at quam urna. Nullam eu aliquet sem, ac rutrum massa. Proin vehicula aliquet lorem, quis hendrerit velit condimentum iaculis. Curabitur non lacus vestibulum, luctus massa vel, ullamcorper tortor. Phasellus a sapien tortor. Curabitur consectetur eget ipsum et scelerisque. Sed porta vel tortor eget maximus. Nam eu sapien nec nisl iaculis laoreet. In hac habitasse platea dictumst. Aenean et sodales tortor. Donec malesuada leo in risus pretium, in consequat justo blandit.

Aenean mauris massa, ornare rutrum dui at, commodo elementum massa. Sed mattis libero odio, sed gravida orci gravida id. Vivamus vulputate iaculis felis ac mollis. Nullam egestas, justo at interdum posuere, elit purus molestie sem, ut congue nulla neque a felis. Etiam efficitur tortor ac tempor vestibulum. Nunc pretium urna non neque pretium, sit amet eleifend nibh tempus. Aliquam sollicitudin ut dolor sed pulvinar. Donec iaculis augue quam, vitae vulputate mi ullamcorper et.

Duis accumsan leo sed turpis pretium dapibus. Proin lobortis condimentum urna et malesuada. Mauris consequat quis urna vitae sollicitudin. Morbi dictum magna sed suscipit vestibulum. Donec at tincidunt libero, at sollicitudin erat. Etiam interdum vel arcu nec pretium. Suspendisse a turpis at libero semper sagittis massa nunc.'''
}

ALL_ARTICLES = [TEN_BYTE_ARTICLE, HUNDRED_BYTE_ARTICLE, THOUSAND_BYTE_ARTICLE, TENTHOUSAND_BYTE_ARTICLE]