scrape_configs:
- job_name: node
  scrape_interval: 5s
  static_configs:
  - targets: ['go-api:9100']

remote_write:
  - url: "http://promscale:9201/write"
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true
