version: "3.9"
services:
  nginx-web:
    build: ./nginx
    hostname: nginx-web
    ports:
      - "80:80"
      - "9100:9100"
    restart: on-failure

  workgen-dev:
    build: ./workgen
    hostname: workgen-dev
    depends_on:
      nginx-web:
        condition: service_started
    restart: on-failure
    entrypoint: ["ab", "-n 1000000", "-c 10", "nginx-web:80/heaviest"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      nginx-web:
        condition: service_started